# Not generated by rust2rpm 21
# https://pagure.io/fedora-rust/rust2rpm/issue/125
%bcond_without check

%global crate rpm-sequoia

Name:           rust-%{crate}
Version:        0.1.0
Release:        1%{?dist}
Summary:        Implementation of the RPM PGP interface using Sequoia

# Upstream license specification: LGPL-2.0-or-later
License:        LGPLv2+
URL:            https://crates.io/crates/rpm-sequoia
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Implementation of the RPM PGP interface using Sequoia.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.txt
%doc README.md
%{_libdir}/librpm_sequoia.so

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
mkdir -p %{buildroot}/%{_libdir}
# FIXME: unversioned .so file can't live in %%{_libdir}
cp -pav target/release/*.so %{buildroot}/%{_libdir}/

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu May 12 2022 Fabio Valentini <decathorpe@gmail.com> - 0.1.0-1
- Initial package
